apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-klaus-hello-world
  name: klaus-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-klaus-hello-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-klaus-hello-world
    spec:
      containers:
      - image: klaus-hello-world:latest
        name: klaus-hello-world
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: KLAUS_PORT
          value: "8080"
